const data = {
    products: [
      {
        id: 1,
        name: "Barra Olímpica",
        category: "Force",
        description: "para poder realizar ejercicios de fuerza",
        price: 5000,
        stock: 5,
        image: "./images/imagen1.jpg",
      },
      {
        id: 2,
        name: "Pesa Rusa Kettlebell",
        category: "Force",
        description: "para poder realizar ejercicios de fuerza",
        price: 3000,
        stock: 10,
        image: "./images/imagen2.jpg",
      }, 
      {
        id: 3,
        name: "Soga de Saltar",
        category: "Resistance",
        description: "para poder realizar ejercicios de resistencia",
        price: 1000,
        stock: 5,
        image: "./images/imagen3.jpg",
      },
      {
        id: 4,
        name: "Rueda Abdominal",
        category: "Resistance",
        description: "para ejercicios de resistencia",
        price: 2000,
        stock: 10,
        image: "./images/imagen4.jpg",
      }, 
      {
        id: 5,
        name: "Bandas de Tubo de Latex",
        category: "Resistance",
        description: "para poder realizar ejercicios de resistencia",
        price: 1500,
        stock: 5,
        image: "./images/imagen5.jpg",
      },
      {
        id: 6,
        name: "Pesos de Tobillo Ajustables",
        category: "Resistance",
        description: "para ejercicios de resistencia",
        price: 2000,
        stock: 10,
        image: "./images/imagen6.jpg",
      }, 
      {
        id: 7,
        name: "Mancuernas",
        category: "Force",
        description: "para realizar ejercicios de fuerza",
        price: 2500,
        stock: 5,
        image: "./images/imagen7.jpg",
      },
      {
        id: 8,
        name: "Bandas Elastica",
        category: "Resistance",
        description: "para ejercicios de resistencia",
        price: 900,
        stock: 10,
        image: "./images/imagen8.jpg",
      },
      {
        id: 9,
        name: "Colchoneta",
        category: "Resistance",
        description: "para ejercicios de resistencia",
        price: 800,
        stock: 5,
        image: "./images/imagen9.jpg",
      }
    ],
  };

export default data;