const data = {
    products: [
      {
        id: 1,
        name: "pesas",
        category: "Force",
        description: "es una pesa para poder realizar ejercicios de fuerza",
        price: 50,
        stock: 5,
        image: "./images/imagen1.jpg",
      },
      {
        id: 2,
        name: "bandas elasticas",
        category: "Resistance",
        description: "bandas para ejercicios de resistencia",
        price: 10,
        stock: 10,
        image: "./images/imagen2.jpg",
      }, {
        id: 3,
        name: "pesas",
        category: "Force",
        description: "es una pesa para poder realizar ejercicios de fuerza",
        price: 50,
        stock: 5,
        image: "./images/imagen1.jpg",
      },
      {
        id: 4,
        name: "bandas elasticas",
        category: "Resistance",
        description: "bandas para ejercicios de resistencia",
        price: 10,
        stock: 10,
        image: "./images/imagen2.jpg",
      }, {
        id: 5,
        name: "pesas",
        category: "Force",
        description: "es una pesa para poder realizar ejercicios de fuerza",
        price: 50,
        stock: 5,
        image: "./images/imagen1.jpg",
      },
      {
        id: 6,
        name: "bandas elasticas",
        category: "Resistance",
        description: "bandas para ejercicios de resistencia",
        price: 10,
        stock: 10,
        image: "./images/imagen2.jpg",
      }, {
        id: 7,
        name: "pesas",
        category: "Force",
        description: "es una pesa para poder realizar ejercicios de fuerza",
        price: 50,
        stock: 5,
        image: "./images/imagen1.jpg",
      },
      {
        id: 8,
        name: "bandas elasticas",
        category: "Resistance",
        description: "bandas para ejercicios de resistencia",
        price: 10,
        stock: 10,
        image: "./images/imagen2.jpg",
      },{
        id: 9,
        name: "pesas",
        category: "Force",
        description: "es una pesa para poder realizar ejercicios de fuerza",
        price: 50,
        stock: 5,
        image: "./images/imagen1.jpg",
      }
    ],
  };

export default data;