export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const PRODUCTS_FROM_CATEGORIES = "PRODUCTS_FROM_CATEGORIES";
export const PRODUCTS_FROM_SEARCH = "PRODUCTS_FROM_SEARCH";